employer_home:
    path:     /Home
    defaults: { _controller: FrontBundle:Pages:employerHome }


freelancer_home:
    path:     /Home
    defaults: { _controller: FrontBundle:Pages:freelancerHome }

front_browseCompanies:
    path:     /companies
    defaults: { _controller: FrontBundle:Pages:browse }

front_Job:
    path:     /job
    defaults: { _controller: FrontBundle:Pages:job }

front_Task:
    path:     /task
    defaults: { _controller: FrontBundle:Pages:task }

front_Company:
    path:     /company
    defaults: { _controller: FrontBundle:Pages:company }

front_TaskList:
    path:     /tasks
    defaults: { _controller: FrontBundle:Pages:taskList }

front_JobsList:
    path:     /jobs
    defaults: { _controller: FrontBundle:Pages:jobList }





front_FindFreelancer:
    path:     /find
    defaults: { _controller: FrontBundle:EmployerPages:findFreelancer }


front_FreelancerProfile:
    path:     /profile
    defaults: { _controller: FrontBundle:Pages:freelancerProfile }


