employer_home:
    path:     /employer
    defaults: { _controller: FrontBundle:Pages:employerHome }


freelancer_home:
    path:     /freelancer
    defaults: { _controller: FrontBundle:Pages:freelancerHome }

front_browseCompanies:
    path:     /browseCompanies
    defaults: { _controller: FrontBundle:Pages:browse }

front_Job:
    path:     /jobPage
    defaults: { _controller: FrontBundle:Pages:job }

front_Task:
    path:     /taskPage
    defaults: { _controller: FrontBundle:Pages:task }

front_Company:
    path:     /freelancer/companyProfile
    defaults: { _controller: FrontBundle:Pages:company }

front_TaskList:
    path:     /tasksList
    defaults: { _controller: FrontBundle:Pages:taskList }

front_JobsList:
    path:     /jobsList
    defaults: { _controller: FrontBundle:Pages:jobList }




front_FindFreelancer:
    path:     /employer/findFreelancer
    defaults: { _controller: FrontBundle:Pages:findFreelancer }


front_FreelancerProfile:
    path:     /freelancerProfile
    defaults: { _controller: FrontBundle:Pages:freelancerProfile }


