bookmark_homepage:
    path:     /
    defaults: { _controller: BookmarkBundle:Default:index }

freelancer_bookmarks:
    path:     /freelancerBookmarks
    defaults: { _controller: BookmarkBundle:Bookmark:freelancerBookmarks }

employer_bookmarks:
    path:     /employerBookmarks
    defaults: { _controller: BookmarkBundle:Bookmark:employerBookmarks }
