note_homepage:
    path:     /
    defaults: { _controller: NoteBundle:Default:index }

self_notes_list:
    path:     /self_notes_list
    defaults: { _controller: NoteBundle:Note:self_notes_list }

delete_self_note:
    path:     /delete_self_note/{id}
    defaults: { _controller: NoteBundle:Note:delete_self_note }

update_self_note:
    path:     /update_self_note/{id}
    defaults: { _controller: NoteBundle:Note:update_self_note }

create_self_note:
    path:     /create_self_note
    defaults: { _controller: NoteBundle:Note:create_self_note }
