dashboard:
    resource: "@DashboardBundle/Resources/config/routing.yml"
    prefix:   /dashboard

bookmark:
    resource: "@BookmarkBundle/Resources/config/routing.yml"
    prefix:   /

job:
    resource: "@JobBundle/Resources/config/routing.yml"
    prefix:   /job

note:
    resource: "@NoteBundle/Resources/config/routing.yml"
    prefix:   /note

bid:
    resource: "@BidBundle/Resources/config/routing.yml"
    prefix:   /bid

offer:
    resource: "@OfferBundle/Resources/config/routing.yml"
    prefix:   /offer

review:
    resource: "@ReviewBundle/Resources/config/routing.yml"
    prefix:   /review

project:
    resource: "@ProjectBundle/Resources/config/routing.yml"
    prefix:   /task

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

homepage:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /



