manage_jobs:
    path:     /manageJobs
    defaults: { _controller: JobBundle:Job:manageJobs }

manage_candidates:
    path:     /managecandidates
    defaults: { _controller: JobBundle:Job:managecandidates }

post_job:
    path:     /postJob
    defaults: { _controller: JobBundle:Job:managecandidates }
