manage_jobs:
    path:     /manage
    defaults: { _controller: JobBundle:Job:manageJobs }

manage_candidates:
    path:     /candidates
    defaults: { _controller: JobBundle:Job:managecandidates }

post_job:
    path:     /post
    defaults: { _controller: JobBundle:Job:managecandidates }
