bids:
    path:     /bids
    defaults: { _controller: BidBundle:Bid:bids }

bidders:
    path:     /bidders
    defaults: { _controller: BidBundle:Bid:manageBidders }

place_bid:
    path:     /place/{deliveryTime?}/{hourlyRate?}
    defaults: { _controller: BidBundle:Bid:placeBid }



