bids:
    path:     /bids
    defaults: { _controller: BidBundle:Bid:bids }

bidders:
    path:     /bidders
    defaults: { _controller: BidBundle:Bid:manageBidders }

place:
    path:     /place
    defaults: { _controller: BidBundle:Bid:createBid }

