rate_employer:
    path:     /rate
    defaults: { _controller: ReviewBundle:Review:rateEmployer }

rate_freelancer:
    path:     /rate
    defaults: { _controller: ReviewBundle:Review:rateFreelancer }
