tasks:
    path:     /projects
    defaults: { _controller: ProjectBundle:Project:projects}

create_task:
    path:     /create_project
    defaults: { _controller: ProjectBundle:Project:createProject }
