tasks:
    path:     /readProject
    defaults: { _controller: ProjectBundle:Project:readProject}

create_task:
    path:     /projectCreate
    defaults: { _controller: ProjectBundle:Project:projectCreate }

list_projects:
    path:     /projects
    defaults: { _controller: ProjectBundle:Project:projects }




list_tasks:
    path:     /projectsList
    defaults: { _controller: ProjectBundle:Project:projectsList }



details_task:
    path:     /details
    defaults: { _controller: ProjectBundle:Project:details }


