tasks:
    path:     /readProject
    defaults: { _controller: ProjectBundle:Project:readProject}

create_task:
    path:     /createProject
    defaults: { _controller: ProjectBundle:Project:createProject }

list_tasks:
    path:     /projectsList
    defaults: { _controller: ProjectBundle:Project:projectsList }

single_task:
    path:     /projectSingle
    defaults: { _controller: ProjectBundle:Project:projectSingle }



