tasks:
    path:     /manage
    defaults: { _controller: ProjectBundle:Project:projects}

create_task:
    path:     /create
    defaults: { _controller: ProjectBundle:Project:createProject }

list_tasks:
    path:     /list
    defaults: { _controller: ProjectBundle:Project:projectsList }

single_task:
    path:     /details
    defaults: { _controller: ProjectBundle:Project:projectSingle }

