create_task:
    path:     /projectCreate
    defaults: { _controller: ProjectBundle:Project:projectCreate }

list_projects:
    path:     /projects
    defaults: { _controller: ProjectBundle:Project:projects }

list_manage_projects:
    path:     /manage_projects
    defaults: { _controller: ProjectBundle:Project:manage_projects }

delete_manage_projects:
    path:     /delete_manage_projects/{id}
    defaults: { _controller: ProjectBundle:Project:delete_manage_projects }





